### ISSUE TITLE
personlisation issue

### ISSUE THREAD

**Issue by imwiththou** [masukomi/kudos#14]
Hi this is Stephen and I am a beginner on HTML and CSS. I found this kudos really fancy and want to put it on my personal site, just below each post. How should I embrace to my page? I tried to pasted related code into my default.html source code but it turned out that the sign appears at the top center of the page, not below the post. Plus no animation can be activated by cursor on it. Something must had gong wrong but I could not find it out... Could you come up with a slightly more detailed instruction on personlisation setup on blog? Thanks so much!

[the aforementioned content had been solved but below comes some new issues]

---

The code can only provide client side statistics which indicating that if uses visit the page with this widget from different browsers, the total counts of "kudos" might be inaccurate. 

It might be improved to make the statistics universal?

**Comment by imwiththou** [comment]
problem solved.

**Comment by masukomi** [comment]
was the solution something that I could add to the docs for other beginners?

I would note that adding the code in this repository is not enough to enable _useful_ kudos on your site. Without some back-end code on the server there is nothing to increment the count across users. If a hundred people click on it there will be 100 cookies on 100 browsers each recording one kudo, but nothing on the server to keep track of, and sum up all those clicks, and thus show a count of 100 when the next person comes to the site.  This is just the client--side code.

**Comment by imwiththou** [comment]
Yes that's one main problem, the code is client side. It is enough to lead this new concept of "likes" as that on Facebook but it will not be correctly report "likes" statistics out. One of my friend suggest to use Facebook or Twitter's API for this but I felt that would be too messy. I wonder if there can be some improvement on the code so that the statistics can be universal instead of only depending on browsers and clients.

**Comment by masukomi** [comment]
No, this is a fundamental issue of web development. Without the client you can't send information to the server. WIthout the server you can't share information between clients. You need both. Twitter's API is totally inappropriate because it has no mechanism whatsoever for this. Facebook's likes would work, but not for powering this. You could probably hook the Kudos into their likes API but I suspect that using something other than their thumb widget or something that made no indication of creating a facebook like by interacting with something would violate their terms of service.

Even if you did use facebook code you'd still be depending on server-side code. 

It simply IS NOT POSSIBLE to do this without server-side code given the current capabilities of web browsers. 

This codebase specifically does not contain back-end code because it would not only be different in every language it would be different in every framework, and different in every usage of every framework. The problem is very simple to solve, but how one would go about it would be unique to how you are choosing to track user interactions.

**Comment by imwiththou** [comment]
I am getting what you are talking about. So the thing that Kudos can bring to us is only the joy of a new appearance of a voting system? lol. Anyway thanks so much for your help. :)

**Comment by masukomi** [comment]
You are correct. This library is merely a pretty interface to a voting system. It does not count up the votes itself.

I have updated the README with more details.
